export const STORY_SECTIONS = [
  {
    id: "raw",
    title: "RAW IDEA",
    subtitle: "POTENTIAL BEFORE FORM.",
    desc: "Every system starts as raw potential.",
    frameStart: 1,
    frameEnd: 80,
  },
  {
    id: "understand",
    title: "UNDERSTAND",
    subtitle: "CLARITY BEFORE ACTION.",
    desc: "We analyze and define what matters.",
    frameStart: 81,
    frameEnd: 160,
  },
  {
    id: "plan",
    title: "PLAN",
    subtitle: "STRUCTURE FROM VISION.",
    desc: "Vision becomes structure.",
    frameStart: 161,
    frameEnd: 240,
  },
  {
    id: "design",
    title: "DESIGN",
    subtitle: "FORM FOLLOWS INTENTION.",
    desc: "We shape ideas into form.",
    frameStart: 241,
    frameEnd: 320,
  },
  {
    id: "development",
    title: "DEVELOPMENT",
    subtitle: "SYSTEMS BENEATH THE SURFACE.",
    desc: "Systems come alive.",
    frameStart: 321,
    frameEnd: 400,
  },
  {
    id: "testing",
    title: "TESTING",
    subtitle: "TRUST THROUGH VERIFICATION.",
    desc: "Everything is verified.",
    frameStart: 401,
    frameEnd: 480,
  },
  {
    id: "launch",
    title: "LAUNCH",
    subtitle: "MOMENTUM INTO MOTION.",
    desc: "The product takes flight.",
    frameStart: 481,
    frameEnd: 560,
  },
  {
    id: "scale",
    title: "SCALE",
    subtitle: "BUILT TO GROW GLOBALLY.",
    desc: "We build what grows globally.",
    frameStart: 561,
    frameEnd: 724,
  },
];
